language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mikeriver/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mikeriver/react-test npm run test -- --coverage

after_success:
  - docker build -t mikeriver/client ./client
  - docker build -t mikeriver/nginx ./nginx
  - docker build -t mikeriver/server ./server
  - docker build -t mikeriver/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mikeriver/client
  - docker push mikeriver/nginx
  - docker push mikeriver/server
  - docker push mikeriver/worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-110737947154"
  bucket_path: "docker-multi"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: main
  skip_cleanup: true

#deploy:
#  provider: elasticbeanstalk
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key_id: $AWS_SECRET_KEY
#  region: "eu-central-1"
#  app: "docker-react"
#  env: "Dockerreact-env"
#  bucket_name: "elasticbeanstalk-eu-central-1-110737947154"
#  bucket_path: "docker-react"
#  on:
#    branch: main
#  skip_cleanup: true