language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mikeriver/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mikeriver/react-test npm run test -- --coverage

after_success:
  - docker build -t mikeriver/client ./client
  - docker build -t mikeriver/nginx ./nginx
  - docker build -t mikeriver/server ./server
  - docker build -t mikeriver/worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mikeriver/client
  - docker push mikeriver/nginx
  - docker push mikeriver/server
  - docker push mikeriver/worker